#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

ENV_FILE=".vps-wizard.env"
TOTAL_STAGES=7

ssh_run() { ssh "$SSH_HOST" "$1"; }
ssh_tty()  { ssh -t "$SSH_HOST" "$1"; }

banner "routewisp: install on a VPS"

# ── Stage 1: connect ────────────────────────────────────────────────────────
stage "VPS connection"
say "SSH access to a running Ubuntu/Debian VPS, port already open to the internet."
ask SSH_HOST "SSH target (user@host, key auth already working):"
write_env SSH_HOST "$SSH_HOST"
say "Testing the connection..."
if ! ssh_run "echo ok" >/dev/null 2>&1; then
  warn "couldn't SSH to $SSH_HOST — fix that (ssh $SSH_HOST manually) and re-run this wizard."
  exit 1
fi
REMOTE_HOME=$(ssh_run 'echo $HOME')
BUN_BIN="$REMOTE_HOME/.bun/bin/bun"
say "Connected (remote \$HOME is $REMOTE_HOME)."
pause

# ── Stage 2: bun + the code ─────────────────────────────────────────────────
stage "Bun + the code"
ask INSTALL_DIR "Install directory on the VPS:"
[[ -z "$INSTALL_DIR" ]] && INSTALL_DIR="$REMOTE_HOME/routewisp"
write_env INSTALL_DIR "$INSTALL_DIR"
if ssh_run "test -x '$BUN_BIN'" >/dev/null 2>&1; then
  say "Bun already installed on the VPS."
else
  confirm "Install Bun on the VPS now (curl -fsSL https://bun.sh/install | bash)?" \
    && ssh_run "curl -fsSL https://bun.sh/install | bash" \
    || { warn "Bun is required — install it yourself, then re-run."; exit 1; }
fi
if ssh_run "test -d '$INSTALL_DIR/.git'" >/dev/null 2>&1; then
  say "Repo already present at $INSTALL_DIR — pulling latest."
  ssh_run "cd '$INSTALL_DIR' && git pull"
else
  ssh_run "git clone https://github.com/mhrmnvl/routewisp.git '$INSTALL_DIR'"
fi
say "Installing dependencies (bun install)..."
ssh_run "cd '$INSTALL_DIR' && '$BUN_BIN' install"
pause "Code + deps are on the VPS."

# ── Stage 3: secrets + .env ──────────────────────────────────────────────────
stage "Configuration (.env on the VPS)"
say "These land in $INSTALL_DIR/.env on the VPS — never committed anywhere."
ask PORT "Port routewisp listens on:"; [[ -z "$PORT" ]] && PORT="20128"
ask_secret ADMIN_TOKEN "ADMIN_TOKEN (blank = generate one now):"
[[ -z "$ADMIN_TOKEN" ]] && ADMIN_TOKEN=$(openssl rand -hex 32)
ask_secret API_KEY_SECRET "API_KEY_SECRET (blank = generate one now):"
[[ -z "$API_KEY_SECRET" ]] && API_KEY_SECRET=$(openssl rand -hex 32)
ask_secret MACHINE_ID_SALT "MACHINE_ID_SALT (blank = generate one now):"
[[ -z "$MACHINE_ID_SALT" ]] && MACHINE_ID_SALT=$(openssl rand -hex 16)
write_env PORT "$PORT"
write_env ADMIN_TOKEN "$ADMIN_TOKEN"
write_env API_KEY_SECRET "$API_KEY_SECRET"
write_env MACHINE_ID_SALT "$MACHINE_ID_SALT"
ssh_run "cat > '$INSTALL_DIR/.env' <<EOF
PORT=$PORT
HOSTNAME=0.0.0.0
DATA_DIR=$INSTALL_DIR/data
ADMIN_TOKEN=$ADMIN_TOKEN
API_KEY_SECRET=$API_KEY_SECRET
MACHINE_ID_SALT=$MACHINE_ID_SALT
RATE_LIMIT_PER_MINUTE=60
EOF"
note "ADMIN_TOKEN saved locally in $ENV_FILE too — you'll need it for the CLI."
pause

# ── Stage 4: smoke test before wiring systemd ───────────────────────────────
stage "Smoke test"
say "Running it in the foreground for a few seconds to catch problems early."
ssh_run "cd '$INSTALL_DIR' && set -a && . ./.env && set +a && timeout 5 '$BUN_BIN' server.js || true"
if ssh_run "cd '$INSTALL_DIR' && set -a && . ./.env && set +a && (timeout 4 '$BUN_BIN' server.js &) && sleep 2 && curl -sf http://localhost:$PORT/api/health" >/dev/null 2>&1; then
  say "Health check OK."
else
  warn "Health check didn't respond — check the output above before continuing."
  confirm "Continue anyway?" || exit 1
fi
pause

# ── Stage 5: systemd (needs sudo on the VPS) ────────────────────────────────
stage "Run under systemd"
say "So it survives reboots and crash-restarts instead of a background shell."
confirm "Install and enable the systemd service now (asks for your sudo password on the VPS)?" && {
  REMOTE_USER=$(ssh_run "whoami")
  ssh_run "cat > /tmp/routewisp.service <<EOF
[Unit]
Description=routewisp
After=network.target

[Service]
Type=simple
User=$REMOTE_USER
WorkingDirectory=$INSTALL_DIR
EnvironmentFile=$INSTALL_DIR/.env
ExecStart=$BUN_BIN server.js
Restart=always
RestartSec=3
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF"
  ssh_tty "sudo mv /tmp/routewisp.service /etc/systemd/system/routewisp.service && sudo systemctl daemon-reload && sudo systemctl enable --now routewisp"
  sleep 2
  ssh_run "curl -sf http://localhost:$PORT/api/health" >/dev/null 2>&1 \
    && say "Service is up (systemctl status routewisp on the VPS to check any time)." \
    || warn "Service didn't respond after starting — SSH in and check: systemctl status routewisp"
}
pause

# ── Stage 6: TLS (optional) ──────────────────────────────────────────────────
stage "TLS (optional)"
say "Needs a domain's A record already pointed at this VPS's IP."
if confirm "Set up HTTPS via Caddy now?"; then
  ask DOMAIN "Domain (e.g. router.example.com):"
  write_env DOMAIN "$DOMAIN"
  if command -v dig >/dev/null 2>&1; then
    VPS_IP=$(ssh_run "curl -s https://api.ipify.org" 2>/dev/null || true)
    DOMAIN_IP=$(dig +short "$DOMAIN" | tail -n1)
    if [[ -n "$VPS_IP" && -n "$DOMAIN_IP" && "$VPS_IP" != "$DOMAIN_IP" ]]; then
      warn "$DOMAIN resolves to $DOMAIN_IP, not the VPS's $VPS_IP — fix DNS first or Let's Encrypt will fail."
      confirm "Continue anyway?" || DOMAIN=""
    fi
  fi
  if [[ -n "$DOMAIN" ]]; then
    if ssh_run "command -v caddy" >/dev/null 2>&1; then
      say "Caddy already installed."
    else
      say "Adding Caddy's official apt repo (plain 'apt install caddy' isn't in the default repos)."
      ssh_tty "sudo apt-get update && sudo apt-get install -y debian-keyring debian-archive-keyring apt-transport-https curl \
        && curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg \
        && curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list \
        && sudo apt-get update && sudo apt-get install -y caddy"
    fi
    ssh_run "cat > /tmp/Caddyfile <<EOF
$DOMAIN {
	reverse_proxy localhost:$PORT
}
EOF"
    ssh_tty "sudo mv /tmp/Caddyfile /etc/caddy/Caddyfile && sudo systemctl reload caddy || sudo systemctl restart caddy"
    say "HTTPS should be live at https://$DOMAIN once Let's Encrypt issues the cert (usually under a minute)."
  fi
else
  note "Skipped — routewisp stays on plain HTTP. Firewall port $PORT to known client IPs."
fi
pause

# ── Stage 7: backups (optional) ──────────────────────────────────────────────
stage "Daily backups (optional)"
if confirm "Add a daily cron job backing up $INSTALL_DIR/data?"; then
  ssh_run "chmod +x '$INSTALL_DIR/deploy/backup.sh'"
  ssh_run "(crontab -l 2>/dev/null | grep -vF '$INSTALL_DIR/deploy/backup.sh'; echo \"17 3 * * * DATA_DIR=$INSTALL_DIR/data $INSTALL_DIR/deploy/backup.sh\") | crontab -"
  say "Backups land in ~/routewisp-backups on the VPS, kept 14 days."
else
  note "Skipped — deploy/backup.sh is still there whenever you want it."
fi

if [[ -n "${DOMAIN:-}" ]]; then
  API_URL="https://$DOMAIN"
else
  API_URL="http://${SSH_HOST#*@}:$PORT"
fi

finish
say "From your own machine (not the VPS):"
step "node bin/routewisp.mjs config set --api-url $API_URL --token $ADMIN_TOKEN"
step "node bin/routewisp.mjs providers add commandcode --api-key ..."
step "node bin/routewisp.mjs providers login antigravity"
